### ISSUE TITLE
flatpak support

### ISSUE THREAD

**Issue by allaeddineomc** [zhangyuannie/butter#8]
### Describe the problem your feature would solve
this app is great but its not available on all distros (including the one i use , fedora silverblue) and flatpak will be the quickest way to get it to the hands of users

### Describe the solution you'd like
package the app as a flatpak and distrobute on flathub , as far as i know system apps like this can be packaged as flatpaks but might have to not use a sandbox

### Describe alternatives you've considered
maybe an appimage is a good alternative but keeping an appimage updated will require a built in update mechanism which might be harder to implement than supporting flatpak

**Comment by zhangyuannie** [comment]
I am not against it. However, I'm not sure how many hacks are needed to make it work given that it needs to interact with the kernel, the filesystem and systemd-timer. None of them can be done in a sandbox currently.

I took a quick glance and apps like Gnome Disks and GParted are not packaged as flatpak either.

For Silverblue, you can either layer it or compile it yourself with `DESTDIR=/opt` for now.

**Comment by allaeddineomc** [comment]
i don't know much about how to skip the sandbox but there is a terminal app called blackbox that is publushed as a flatpak and runs without a sandbox and have no problem accessing sudo and systemctl commands so i think checking how they do it will be very helpful

**Comment by zhangyuannie** [comment]
They use flatpak-spawn which let them run arbitrary command on the host. However, Butter mostly uses syscalls (via libraries) directly instead of executing shell commands. So if we want to go this way, we would need to put Butter or at the very least some part of Butter on the host directly.

**Comment by allaeddineomc** [comment]
this is very possible , you can use ```$HOME/.var/app/zhangyuannie/butter/``` directory to keep copies of the files and this won't require additional permissions  , otherwise you can keep all the program files inside the flatpak and instead of accessing them normally access them from ```/var/lib/flatpak/app/zhangyuannie/butter/....```  on the host , in thiis case you will need the system files access permission

**Comment by deusnovus** [comment]
Maybe a popup screen on initial startup letting you know how to set filesystem access via Flatseal before proceeding to the app? I obviously much prefer using flatpaks nowadays, but I'd honestly be perfectly fine with an RPM package on GNOME Software, like btrfs-assistant.

**Comment by Batwam** [comment]
deb file for Debian bases distros would be very nice too, or even a snap...

**Comment by DadiBit** [comment]
Hi there! Just got into Fedora Silverblue and wanted to share my findings on the topic:

## Building on GNOME SDK

Mainfest looks like this:
```yaml
id: org.znie.Butter
runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk
command: butter
finish-args:
  - --allow=system-service
  - --socket=pulseaudio
  - --socket=session-bus
  - --talk-name=org.freedesktop.systemd1
add-build-extensions:
  org.freedesktop.Sdk.Extension.rust-stable:
    version: '24.08'
    directory: .
modules:
  - name: butter
    buildsystem: meson
    config-opts: [ "--prefix=/app" ]
    sources:
      - type: git
        url: "https://github.com/zhangyuannie/butter.git"
        branch: main
```
Compiling with `flatpak run org.flatpak.Builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir org.znie.Butter.yml` fails when looking for systemd. I have yet to find a solution on how to get the build step to interact with systemd.

## Building on Fedora SDK

I stumbled on [this](http://janberan.tech/2021/02/rpm2flatpak/) cool blog post, however it's quite outdated: fedmod is apparently dead since a long time.
